apps/carrito/urls.py
from django.urls import path , include
from apps.carrito.views import *
from django.contrib.auth import views as auth_views
from apps.carrito import views

#from apps.accounts.decorators import check_recaptcha

app_name = 'carrito'

urlpatterns = [

    path('checkout/', checkout, name='checkout'),
    path('orden_detalle/', orden_detalle, name='orden_detalle'),
    path('agregar_a_carrito/<item_id>', agregar_a_carrito, name='agregar_a_carrito'),
    path('actualizar-transaccion/<token>', checkout, name='actualizar_transaccion'),
    path('borrar_de_carrito/<item_id>', borrar_de_carrito, name='borrar_de_carrito'),
    path('payment/<order_id>', process_payment, name='proceso_pago'),
    
    
    # url(r'^success/$', success, name='purchase_success'),

]

apps/productos/urls.py
from django.urls import path , include
from apps.productos.views import *
from django.contrib.auth import views as auth_views
from apps.productos import views

#from apps.accounts.decorators import check_recaptcha

app_name = "productos"

urlpatterns = [
    path('listar-productos', views.ProductosListar.as_view(), name='productos_listar'),
    path('listar-productos/<int:pk>', views.ProductoDetalle.as_view(), name='producto_detalle'),
    path('crear-producto', views.ProductoCrear.as_view(), name='producto_crear'),
    path('actualizar-producto/<int:pk>', views.ProductoActualizar.as_view(), name='producto_actualizar'),
    path('eliminar-producto/<int:pk>', views.ProductoEliminar.as_view(), name='producto_eliminar'),

    path('crear-combo', views.ComboCrear.as_view(), name='combo_crear'),
    path('listar-combos', views.ComboListar.as_view(), name='combos_listar'),


    path('listar-ingredientes', views.IngredientesListar.as_view(), name='ingredientes_listar'),
    path('listar-ingredientes/<int:pk>', views.IngredienteDetalle.as_view(), name='ingrediente_detalle'),
    path('crear-ingrediente', views.IngredienteCrear.as_view(), name='ingrediente_crear'),
    path('actualizar-ingrediente/<int:pk>', views.IngredienteActualizar.as_view(), name='ingrediente_actualizar'),
    path('eliminar-ingrediente/<int:pk>', views.IngredienteEliminar.as_view(), name='ingrediente_eliminar'),


    path('nuestro-menu/', views.Tienda.as_view(template_name='productos/menu.html'), name='menu'),
    path('tienda/', views.Tienda.as_view(template_name='productos/tienda.html'), name='tienda'),
    path('ver-item/<int:pk>', views.Item.as_view(template_name='productos/item.html'), name='item'),

]

apps/usuarios/urls.py
from django.urls import path , include
from apps.usuarios.views import *
from django.contrib.auth import views as auth_views
from apps.usuarios import views
#from apps.accounts.decorators import check_recaptcha

app_name = 'usuarios'

urlpatterns = [
    path('home', home, name='home'),
    path('dashboard', dashboard, name='dashboard'),
    path('registro', views.Registro.as_view(), name='registrarme'),
    path('mi-cuenta/<int:pk>', views.DatosActualizar.as_view(template_name='usuarios/datos.html'), name='datos'),
    path('contrasena/<int:pk>', views.ContrasenaActualizar.as_view(template_name='usuarios/contrasena.html'), name='contrasena'),
    path('desactivar/<int:id_usuario>', usuario_desactivar, name='desactivar'),

    path('crear-digitador', views.CrearDigitador.as_view(template_name='usuarios/digitador_crear.html'), name='crear_digitador'),
    path('listar-digitadores', views.DigitadoresListar.as_view(template_name='usuarios/digitador_list.html'), name='listar_digitadores'),
    path('ver-digitador/<int:pk>', views.UsuarioDetalle.as_view(template_name='usuarios/digitador_detail.html'), name='digitador_detalle'),
    path('pdf-digitadores/<int:staff>', pdf_usuario, name='pdf_digitadores'),

    path('listar-clientes', views.ClientesListar.as_view(template_name='usuarios/cliente_list.html'), name='listar_clientes'),
    path('ver-cliente/<int:pk>', views.UsuarioDetalle.as_view(template_name='usuarios/cliente_detail.html'), name='cliente_detalle'),
    path('pdf-clientes/<staff>', pdf_usuario, name='pdf_clientes'),


    path('login', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='usuarios/login.html'),
         name='login'),


    path('salir', auth_views.LogoutView.as_view(), name='salir'),
]

apps/carrito/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from apps.usuarios.models import Usuario
from apps.productos.models import Producto
from django.db.models.signals import post_save
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

class Perfil(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Producto, blank=True)
    stripe_id = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.usuario.username


def post_guardar_perfil(sender, instance, created, *args, **kwargs):
    user_profile, created = Perfil.objects.get_or_create(usuario=instance)

    if user_profile.stripe_id is None or user_profile.stripe_id == '':
        new_stripe_id = stripe.Customer.create(email=instance.email)
        user_profile.stripe_id = new_stripe_id['id']
        user_profile.save()


post_save.connect(post_guardar_perfil, sender=Usuario)

class ItemCarrito(models.Model):
    producto = models.OneToOneField(Producto, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.producto.nombre


class Carrito(models.Model):
    cod_ref = models.CharField(max_length=15)
    owner = models.ForeignKey(Perfil, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(ItemCarrito)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_carrito_items(self):
        return self.items.all()

    def get_carrito_total(self):
        return sum([item.producto.precio for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.cod_ref)


    
class Transaccion(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    orden_id = models.CharField(max_length=120)
    cantidad = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

apps/usuarios/models.py
from django.db import models
from cities_light.models import City
from django.contrib.auth.models import AbstractUser
from apps.productos.models import Producto


class Usuario(AbstractUser):

    documento = models.CharField(max_length=20)
    ciudad = models.ForeignKey(City, on_delete=models.PROTECT, related_name='cities_light_city', null=True)
    barrio = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)
    USERNAME_FIELD = 'username'

apps/usuarios/forms.py
from django import forms
from .models import *

class ContactForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    correo = forms.EmailField()
    mensaje = forms.CharField(widget=forms.Textarea)

apps/carrito/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from apps.productos.models import Producto
from django.db import connection
from apps.tenants.models import *

from apps.carrito.extras import generar_orden_id, transact, generar_token_cliente
from apps.carrito.models import ItemCarrito, Carrito, Transaccion, Perfil

import datetime
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY


def mi_perfil(request):
	mi_usuario_perfil = Perfil.objects.filter(usuario=request.user).first()
	mis_ordenes = Carrito.objects.filter(is_ordered=True, owner=mi_usuario_perfil)
	context = {
		'mis_ordenes': mis_ordenes
	}

	return render(request, "productos:tienda", context)

def get_orden_usuario_pendiente(request):
    # get order for the correct user
    perfil_usuario = get_object_or_404(Perfil, usuario=request.user)
    carrito = Carrito.objects.filter(owner=perfil_usuario, is_ordered=False)
    if carrito.exists():
        # get the only order in the list of filtered orders
        return carrito[0]
    return 0


@login_required()
def agregar_a_carrito(request, **kwargs):
    # get the user profile
    perfil_usuario = get_object_or_404(Perfil, usuario=request.user)
    # filter products by id
    producto = Producto.objects.filter(id=kwargs.get('item_id', "")).first()
    # check if the user already owns this product
    if producto in request.user.perfil.productos.all():
        messages.error(request, 'Este producto ya está en el carrito')
        return redirect(reverse('productos:tienda'))
    # create orderItem of the selected product
    orden_item, status = ItemCarrito.objects.get_or_create(producto=producto)
    # create order associated with the user
    orden_usuario, status = Carrito.objects.get_or_create(owner=perfil_usuario, is_ordered=False)
    orden_usuario.items.add(orden_item)
    if status:
        # generate a reference code
        orden_usuario.cod_ref = generar_orden_id()
        orden_usuario.save()

    # show confirmation message and redirect back to the same page
    messages.success(request, "Producto agregado al carrito!")
    return redirect(reverse('productos:tienda'))


@login_required()
def borrar_de_carrito(request, item_id):
    item_a_borrar = ItemCarrito.objects.filter(pk=item_id)
    if item_a_borrar.exists():
        item_a_borrar[0].delete()
        messages.info(request, "Producto borrado")
    return redirect(reverse('carrito:orden_detalle'))


@login_required()
def orden_detalle(request, **kwargs):
		usuario = request.user
		schema = connection.schema_name
		tenant = Tenant.objects.get(schema_name=schema)
		orden_existente = get_orden_usuario_pendiente(request)
		context = {
		'orden': orden_existente,
		'usuario': usuario,
		'total': orden_existente.get_carrito_total(),
		'tenant': tenant,
		}
		return render(request, 'carrito/orden_detalle.html', context)

@login_required()
def checkout(request, **kwargs):
        usuario = request.user
        schema = connection.schema_name
        tenant = Tenant.objects.get(schema_name=schema)
        orden_existente = get_orden_usuario_pendiente(request)
        context = {
            'orden': orden_existente,
            'usuario': usuario,
            'total': orden_existente.get_carrito_total(),
            'tenant': tenant,
        }
        return render(request, 'carrito/checkout.html', context)


@login_required()
def process_payment(request, order_id):
    return redirect(reverse('carrito:update_records',
                            kwargs={
                                'order_id':order_id,
                            })
                    )

@login_required()
def update_transaction_records(request, order_id):
#     # get the order being processed
    order_to_purchase = Carrito.objects.filter(pk=order_id)#get_user_pending_order(request)

     # update the placed order
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()

     # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

     # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

     # Add products to user profile
    user_profile = get_object_or_404(Profile, user=request.user)
     # get the products from the items
    order_products = [item.product for item in order_items]
    user_profile.ebooks.add(*order_products)
    user_profile.save()


     # create a transaction
    transaction = Transaction(profile=request.user.profile,
                            token=token,
                            order_id=order_to_purchase.id,
                            amount=order_to_purchase.get_cart_total(),
                            success=True)
    # save the transcation (otherwise doesn't exist)
    transaction.save()


    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.info(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('accounts:my_profile'))

def success(request, **kwargs):
     # a view signifying the transcation was successful
     return render(request, 'shopping_cart/purchase_success.html', {})

apps/usuarios/templates/usuarios/cliente_detail.html
{% extends 'base_dash.html' %}
{# Load the tag library #}
{% load bootstrap4 %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="{% static 'coffee_template/css/producto-detalle.css' %}">
{% endblock css %}

{% block titulo %} Detalle Cliente {% endblock titulo %}

{% block contenido %}

    <section class="ftco-section center">
        <div class = "container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span>
                <span class="mr-2"><a href="{% url 'usuarios:listar_clientes' %}">Clientes</a></span>
                <span>Ver Cliente</span></p>
            <div class="row justify-content-center">
                <div class="col-xl-8 ftco-animate">
                    <form method="post" enctype="multipart/form-data" action="#" class="billing-form ftco-bg-dark p-3 p-md-5 ">

                        <div class="row justify-content-center">
                            <div class="col-xl-9 ftco-animate">
                                <h3 class="mb-4 billing-heading">Ver Cliente</h3>
                            </div>
                            <div class="col-xl-3 ftco-animate" >
                                <p><a href="{% url 'usuarios:listar_clientes' %}" style="width: 130px;" class="btn btn-white btn-outline-white p-2">Clientes</a></p>
                            </div>
                        </div>

                        <div class="row align-items-end">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Nombres</label>
                                    <input class="form-control" type="text" value="{{object.first_name}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Apellidos</label>
                                    <input class="form-control" type="text" value="{{object.last_name}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Ciudad</label>
                                    <input class="form-control" type="text" value="{{object.ciudad.display_name}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Barrio</label>
                                    <input class="form-control" type="text" value="{{object.barrio}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Dirección</label>
                                    <input class="form-control" type="text" value="{{object.direccion}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Teléfono</label>
                                    <input class="form-control" type="text" value="{{object.telefono}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock contenido %}
{% block js %}
    <script>
    </script>
{% endblock js %}

apps/usuarios/templates/usuarios/cliente_list.html
{% extends 'base_dash.html' %}
{# Load the tag library #}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/tenant-listar.css' %}">
    <style media="screen"></style>
{% endblock css %}

{% block titulo %} Clientes {% endblock titulo %}

{% block contenido %}
    <section class="ftco-section">
        <div class = "container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span>
                <span>Lista de Clientes</span></p>
                    <form action="#" class="billing-form ftco-bg-dark p-3 p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-xl-10 ftco-animate">
                                <h3 class="mb-4 billing-heading">Lista de Clientes</h3>
                            </div>
                            <div class="col-xl-2 ftco-animate">
                                <p><a href="{% url 'usuarios:pdf_clientes' 0 %}" style="width: 143px;" class="btn btn-danger custom-btn p-2">Generar PDF</a></p>
                            </div>
                        </div>
                        <div class="table-responsive">
                          <table id="tabla_items" class="table table-striped">

                            <thead class="thead-dark">
                            <tr>
                                <th style="width: 10.5%" scope="col">Id</th>
                                <th style="width: 10.5%" scope="col">Usuario</th>
                                <th style="width: 10.5%" scope="col">Documento</th>
                                <th style="width: 10.5%" scope="col">Nombres</th>
                                <th style="width: 10.5%" scope="col">Apellidos</th>
                                <th style="width: 12.5%" scope="col">Correo Electrónico</th>
                                <th style="width: 10.5%" scope="col">Estado</th>
                                <th style="width: 14%" scope="col">Acciones</th>
                            </tr>
                            </thead>
                            <tbody >
                            {% for usuario in usuario_list %}
                                <tr>
                                    <td style="width: 5%">
                                        {{usuario.id}}
                                    </td>
                                    <td style="width: 10.5%">
                                        {{usuario.username}}
                                    </td>
                                    <td  style="width: 6%">
                                        {{usuario.documento}}
                                    </td>
                                    <td style="width: 12.5%">
                                        {{usuario.first_name}}
                                    </td>
                                    <td style="width: 18%">
                                        {{usuario.last_name}}
                                    </td>
                                    <td style="width: 10.5%">
                                        {{usuario.email}}
                                    </td>
                                    <td style="width: 8%">
                                        {{ usuario.is_active|yesno:"Activo,Inactivo"}}
                                    </td>
                                    <td style="width: 14%">

                                      <p class="mb-1"><a href="{% url 'usuarios:cliente_detalle' usuario.id %}" class="btn btn-outline-info custom-btn p-2">Ver detalle</a></p>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>

                          </table>
                        </div>

                  </form>
        </div>
    </section>

{% endblock contenido %}

{% block js %}
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/jquery-3.3.1.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#tabla_items').DataTable({
                responsive: true
            });
        } );
    </script>

{% endblock js %}

apps/usuarios/templates/usuarios/dash_admin.html
{% extends 'base_dash.html' %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block titulo %}Dashboard{% endblock titulo %}

{% block contenido %}

{% endblock contenido %}
{% block js %}

{% endblock js %}

apps/usuarios/templates/usuarios/digitador_detail.html
{% extends 'base_dash.html' %}
{# Load the tag library #}
{% load bootstrap4 %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="{% static 'coffee_template/css/producto-detalle.css' %}">
{% endblock css %}

{% block titulo %} Detalle Digitador {% endblock titulo %}

{% block contenido %}

    <section class="ftco-section center">
        <div class = "container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span>
                <span class="mr-2"><a href="{% url 'usuarios:listar_digitadores' %}">Digitadores</a></span>
                <span>Ver Digitador</span></p>
            <div class="row justify-content-center">
                <div class="col-xl-8 ftco-animate">
                    <form method="post" enctype="multipart/form-data" action="#" class="billing-form ftco-bg-dark p-3 p-md-5 ">

                        <div class="row justify-content-center">
                            <div class="col-xl-9 ftco-animate">
                                <h3 class="mb-4 billing-heading">Ver Digitador</h3>
                            </div>
                            <div class="col-xl-3 ftco-animate" >
                                <p><a href="{% url 'usuarios:listar_digitadores' %}" style="width: 130px;" class="btn btn-white btn-outline-white p-2">Digitadores</a></p>
                            </div>
                        </div>

                        <div class="row align-items-end">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Nombres</label>
                                    <input class="form-control" type="text" value="{{object.first_name}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Apellidos</label>
                                    <input class="form-control" type="text" value="{{object.last_name}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Ciudad</label>
                                    <input class="form-control" type="text" value="{{object.ciudad.display_name}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Barrio</label>
                                    <input class="form-control" type="text" value="{{object.barrio}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Dirección</label>
                                    <input class="form-control" type="text" value="{{object.direccion}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Teléfono</label>
                                    <input class="form-control" type="text" value="{{object.telefono}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock contenido %}
{% block js %}
    <script>
    </script>
{% endblock js %}

apps/usuarios/templates/usuarios/digitador_list.html
{% extends 'base_dash.html' %}
{# Load the tag library #}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/tenant-listar.css' %}">
    <style media="screen"></style>
{% endblock css %}

{% block titulo %} Digitadores {% endblock titulo %}

{% block contenido %}
    <section class="ftco-section">
        <div class = "container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span>
                <span>Lista de Digitadores</span></p>
                    <form action="#" class="billing-form ftco-bg-dark p-3 p-md-5">
                        <div class="row justify-content-center">
                            <div class="col-xl-8 ftco-animate">
                                <h3 class="mb-4 billing-heading">Lista de Digitadores</h3>
                            </div>
                            <div class="col-xl-2 ftco-animate">
                                <p><a href="{% url 'usuarios:crear_digitador' %}" style="width: 143px;" class="btn btn-primary p-2">Crear Digitador</a></p>
                            </div>
                            <div class="col-xl-2 ftco-animate">
                                <p><a href="{% url 'usuarios:pdf_digitadores' 1 %}" style="width: 143px;" class="btn btn-danger custom-btn p-2">Generar PDF</a></p>
                            </div>
                        </div>
                        <div class="table-responsive">
                          <table id="tabla_items" class="table table-striped">

                            <thead class="thead-dark">
                            <tr>
                                <th style="width: 10.5%" scope="col">Id</th>
                                <th style="width: 10.5%" scope="col">Usuario</th>
                                <th style="width: 10.5%" scope="col">Documento</th>
                                <th style="width: 10.5%" scope="col">Nombres</th>
                                <th style="width: 10.5%" scope="col">Apellidos</th>
                                <th style="width: 12.5%" scope="col">Correo Electrónico</th>
                                <th style="width: 10.5%" scope="col">Estado</th>
                                <th style="width: 14%" scope="col">Acciones</th>
                            </tr>
                            </thead>
                            <tbody >
                            {% for usuario in usuario_list %}
                                <tr>
                                    <td style="width: 5%">
                                        {{usuario.id}}
                                    </td>
                                    <td style="width: 10.5%">
                                        {{usuario.username}}
                                    </td>
                                    <td  style="width: 6%">
                                        {{usuario.documento}}
                                    </td>
                                    <td style="width: 12.5%">
                                        {{usuario.first_name}}
                                    </td>
                                    <td style="width: 18%">
                                        {{usuario.last_name}}
                                    </td>
                                    <td style="width: 10.5%">
                                        {{usuario.email}}
                                    </td>
                                    <td style="width: 8%">
                                        {{ usuario.is_active|yesno:"Activo,Inactivo"}}
                                    </td>
                                    <td style="width: 14%">

                                      <p class="mb-1"><a href="{% url 'usuarios:digitador_detalle' usuario.id %}" class="btn btn-outline-info custom-btn">Ver detalle</a></p>
                                        <p><a href="#" class="btn btn-outline-danger custom-btn">Desactivar</a></p>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>

                          </table>
                        </div>

                  </form>
        </div>
    </section>

{% endblock contenido %}

{% block js %}
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/jquery-3.3.1.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#tabla_items').DataTable({
                responsive: true
            });
        } );
    </script>

{% endblock js %}