apps/carrito/urls.py
from django.urls import path , include
from apps.carrito.views import *
from django.contrib.auth import views as auth_views
from apps.carrito import views

#from apps.accounts.decorators import check_recaptcha

app_name = 'carrito'

urlpatterns = [

    path('checkout/', checkout, name='checkout'),
    path('orden_detalle/', orden_detalle, name='orden_detalle'),
    path('agregar_a_carrito/<item_id>', agregar_a_carrito, name='agregar_a_carrito'),
    path('actualizar-transaccion/<token>', checkout, name='actualizar_transaccion'),
    path('borrar_de_carrito/<item_id>', borrar_de_carrito, name='borrar_de_carrito'),
    path('payment/<order_id>', process_payment, name='proceso_pago'),
    
    
    # url(r'^success/$', success, name='purchase_success'),

]

apps/tenants/urls.py
from django.urls import path
from .views import *

app_name = 'tenants'
urlpatterns = [
    path('dashboard', dashboard, name='dashboard'),
    path('crear-tenant', tenant_crear , name='tenant_crear'),
    path('listar-tenants', tenants_listar , name='tenants_listar'),
    path('actualizar-tenant/<int:id_tenant>', tenant_modificar , name='tenant_modificar'),
    path('desactivar-tenant/<int:id_tenant>', tenant_desactivar, name='tenant_desactivar'),
    path('activar-tenant/<int:id_tenant>', tenant_activar, name='tenant_activar'),
]

apps/usuarios/urls.py
from django.urls import path , include
from apps.usuarios.views import *
from django.contrib.auth import views as auth_views
from apps.usuarios import views
#from apps.accounts.decorators import check_recaptcha

app_name = 'usuarios'

urlpatterns = [
    path('home', home, name='home'),
    path('dashboard', dashboard, name='dashboard'),
    path('registro', views.Registro.as_view(), name='registrarme'),
    path('mi-cuenta/<int:pk>', views.DatosActualizar.as_view(template_name='usuarios/datos.html'), name='datos'),
    path('contrasena/<int:pk>', views.ContrasenaActualizar.as_view(template_name='usuarios/contrasena.html'), name='contrasena'),
    path('desactivar/<int:id_usuario>', usuario_desactivar, name='desactivar'),

    path('crear-digitador', views.CrearDigitador.as_view(template_name='usuarios/digitador_crear.html'), name='crear_digitador'),
    path('listar-digitadores', views.DigitadoresListar.as_view(template_name='usuarios/digitador_list.html'), name='listar_digitadores'),
    path('ver-digitador/<int:pk>', views.UsuarioDetalle.as_view(template_name='usuarios/digitador_detail.html'), name='digitador_detalle'),
    path('pdf-digitadores/<int:staff>', pdf_usuario, name='pdf_digitadores'),

    path('listar-clientes', views.ClientesListar.as_view(template_name='usuarios/cliente_list.html'), name='listar_clientes'),
    path('ver-cliente/<int:pk>', views.UsuarioDetalle.as_view(template_name='usuarios/cliente_detail.html'), name='cliente_detalle'),
    path('pdf-clientes/<staff>', pdf_usuario, name='pdf_clientes'),


    path('login', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='usuarios/login.html'),
         name='login'),


    path('salir', auth_views.LogoutView.as_view(), name='salir'),
]

apps/tenants/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django_tenants.models import TenantMixin, DomainMixin
from django_tenants.postgresql_backend.base import _is_valid_schema_name
from apps.usuarios.models import Usuario
from datetime import datetime


class Tenant(TenantMixin):

    TIPOS_PAQUETES = (
        ("BÁSICO", "Básico"),
        ("STANDARD", "Standard"),
        ("PREMIUM", "Premium"),
    )

    """
    Modelo que representará a los tenants en el sistema
    """
    nombre = models.CharField(max_length=100,  blank=False)
    direccion = models.CharField(max_length=100,  blank=False)
    telefono = models.CharField(max_length=100,  blank=False)
    paquete = models.CharField(max_length=10, choices=TIPOS_PAQUETES)
    pagado_hasta = models.DateField(default=datetime.now)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre


class Dominio(DomainMixin):
    """
    Modelo que representará al dominio en el sistema
    """
    pass

apps/tenants/forms.py
from django import forms
from .models import *


class TenantForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        from django.conf import settings
        super(TenantForm, self).__init__(*args, **kwargs)
        self.fields['schema_name'].label = "Subdominio *"

    class Meta:
        model = Tenant
        fields = ('nombre', 'pagado_hasta', 'paquete', 'direccion', 'telefono', 'schema_name',)

    def clean_schema_name(self):
        dir_tenant = self.cleaned_data["schema_name"]
        if dir_tenant.lower() == 'www':
            self.add_error("schema_name", "No es posible registrar %s como dirección en el sistema" % dir_tenant)

        return dir_tenant


class ModificarTenantForm(forms.ModelForm):
    class Meta:
        model = Tenant
        fields = ('nombre', 'paquete', 'direccion', 'telefono', 'estado',)

apps/tenants/views.py
from django.conf import settings
from django.contrib import messages
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.db import connection
from django.core.mail import send_mail, EmailMessage
# Create your views here.





def dashboard(request):
    schema = connection.schema_name
    usuario = request.user
    public = Tenant.objects.get(schema_name=schema)
    return render(request, 'tenants/dash_super.html', {'public': public, 'usuario': usuario})


def tenant_crear(request):
    schema = connection.schema_name
    usuario = request.user
    public = Tenant.objects.get(schema_name=schema)
    form = TenantForm()
    if request.method == 'POST':
        form = TenantForm(request.POST)
        if form.is_valid():
            try:
                """
                La operación se maneja como transaccional dado que involucra la creación de más de un objeto los cuales
                estan relacionados
                """
                with transaction.atomic():
                    tenant = form.save()
                    """
                    Se crea el dominio y se le asocia información alojada en el tenant. En este punto es que sucede la
                    creación del esquema del tenant en la base de datos
                    """
                    Dominio.objects.create(domain='%s%s' % (tenant.schema_name, settings.DOMAIN), is_primary=True, tenant=tenant)
                    messages.success(request, "El tenant se ha registrado correctamente")
            except Exception:
                messages.error(request, 'Ha ocurrido un error durante la creación del tenant, se abortó la operación')
            return redirect('tenants:tenants_listar')
        else:
            messages.error(request, "Por favor verificar los campos en rojo")
    return render(request, 'tenants/tenant_form.html', {'form': form, 'public': public, 'usuario': usuario})


def tenants_listar(request):
    usuario = request.user
    dominios = Dominio.objects.exclude(tenant__schema_name='public').select_related('tenant')
    return render(request, 'tenants/tenant_list.html', {'dominios': dominios, 'usuario': usuario})


def tenant_modificar(request, id_tenant):
    usuario = request.user
    tenant = Tenant.objects.get(id=id_tenant)
    if request.method == 'POST':
        form = TenantForm(request.POST, request.FILES, instance=tenant)
        if form.is_valid():
            form.save()
            messages.success(request, 'Tenant modificada exitosamente!')
            return redirect('tenants:tenants_listar')
        else:
            messages.error(request, 'Por favor corrige los errores')
            return render(request, 'tenants/tenant_form.html', {'form': form, 'usuario': usuario})
    else:
        form = TenantForm(instance=tenant)
        return render(request, 'tenants/tenant_form.html', {'form': form, 'usuario': usuario})


def tenant_desactivar(request, id_tenant):
    tenant = Tenant.objects.get(id=id_tenant)
    tenant.estado = False
    Dominio.objects.delete(tenant_id=id_tenant)


def tenant_activar(request, id_tenant):
    tenant = Tenant.objects.get(id=id_tenant)
    tenant.estado = True
    Dominio.objects.create(domain='%s%s' % (tenant.schema_name, settings.DOMAIN), is_primary=True, tenant=tenant)

apps/tenants/templates/tenants/home_franquicia.html
{% extends 'base_maravilla.html' %}
{% load staticfiles %}
{% load bootstrap4 %}



{% block css %}
    <style type="text/css">

        .paquete {
            border-color: #c49b63 !important;
            box-shadow: 5px 10px #c49b63;
            background-color: black !important;
        }
    </style>


{% endblock css %}
{% block titulo %}Home{% endblock titulo %}


{% block contenido %}
    <section class="home-slider owl-carousel">
        <div class="slider-item" style="background-image: url({% static 'images/b0.jpg' %});">
            <div class="overlay"></div>
            <div class="container">
                <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">
                    <div class="col-md-8 col-sm-12 text-center ftco-animate">
                        <span class="subheading">Bienvenido</span>
                        <h1 class="mb-4">Franquicias Maravilla</h1>
                        <p class="mb-4 mb-md-5">La empresa Maravilla es una franquicia individual de carácter nacional para la elaboración, producción, promoción y comercialización de alimentos procesados en diferentes líneas.
                            Cada uno de los productos que ofrecemos es elaborado y producido con la mejor calidad.</p>
                        <p><a href="#section-counter" class="btn btn-primary p-3 px-xl-4 py-xl-3">Crea Tu Franquicia Ahora</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="slider-item" style="background-image: url({% static 'images/b1.jpg' %});">
            <div class="overlay"></div>
            <div class="container">
                <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

                    <div class="col-md-8 col-sm-12 text-center ftco-animate">
                        <span class="subheading">Bienvenido</span>
                        <h1 class="mb-4">Los mejores productos</h1>
                        <p class="mb-4 mb-md-5">Pollo, pastas, comidas rápidas, fritos, bebidas, carnes, pescados, menú infantil y la línea de combos.</p>
                        <p><a href="#section-counter" class="btn btn-primary p-3 px-xl-4 py-xl-3">Crea Tu Franquicia Ahora</a>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <section class="ftco-gallery">
        <div class="container-wrap">
            <div class="row no-gutters">
                <div class="col-md-3 ftco-animate">
                    <a href="#" class="gallery img d-flex align-items-center"
                       style="background-image: url({% static 'images/gal1.jpg' %});">
                    </a>
                </div>
                <div class="col-md-3 ftco-animate">
                    <a href="#" class="gallery img d-flex align-items-center"
                       style="background-image: url({% static 'images/gal2.jpg' %});">
                    </a>
                </div>
                <div class="col-md-3 ftco-animate">
                    <a href="#" class="gallery img d-flex align-items-center"
                       style="background-image: url({% static 'images/gal3.jpg' %});">
                    </a>
                </div>
                <div class="col-md-3 ftco-animate">
                    <a href="#" class="gallery img d-flex align-items-center"
                       style="background-image: url({% static 'images/gal4.jpg' %});">
                    </a>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-counter ftco-bg-dark img" id="section-counter" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <h2 class="mb-4 text-center text-primary" style="font-family: 'Great Vibes', cursive;">Nuestros Paquetes</h2>
            <div class="row">
                <div class="col-md-12">
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-lg-3 m-2 d-flex border p-4 paquete">
                            <div class="block-50 text-center">
                                <div class="text">
                                    <h3 class="ftco-services">Básico</h3>
                                    <strong class="number"><p>$50.00</p></strong>
                                    <div class="ftco-bg-dark p-2" style="color: #c49b63 !important;">
                                        <p>Una cosa que sirve para algo</p>
                                        <p>Otra cosa que también puede servir</p>
                                    </div>
                                    <p class="pt-3"><a href="#adquirir_franquicia" class="btn btn-primary btn-outline-primary" data-toggle="modal" data-target="#contactar">Adquirir Paquete</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 m-2 d-flex justify-content-center border p-4 paquete">
                            <div class="block-50 text-center">
                                <div class="text">
                                    <h3 class="ftco-services">Premium</h3>
                                    <strong class="number"><p>$200.00</p></strong>
                                    <div class="ftco-bg-dark p-2" style="color: #c49b63 !important;">
                                        <p>Una cosa que sirve para algo</p>
                                        <p>Otra cosa que también puede servir</p>
                                    </div>
                                    <p class="pt-3"><a href="#adquirir_franquicia" class="btn btn-primary btn-outline-primary" data-toggle="modal" data-target="#contactar">Adquirir Paquete</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 m-2 d-flex justify-content-center border p-4 paquete">
                            <div class="block-50 text-center">
                                <div class="text">
                                    <h3 class="ftco-services">Standard</h3>
                                    <strong class="number"><p>$100.00</p></strong>
                                    <div class="ftco-bg-dark p-2" style="color: #c49b63 !important;">
                                        <p>Una cosa que sirve para algo</p>
                                        <p>Otra cosa que también puede servir</p>
                                    </div>
                                    <p class="pt-3"><a href="#adquirir_franquicia" class="btn btn-primary btn-outline-primary" data-toggle="modal" data-target="#contactar">Adquirir Paquete</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="contactar">
        <div class="modal-dialog">
            <div class="modal-content ftco-bg-dark" >
                <div class="modal-body">
                    <div class="row justify-content-center">
                        <div class="col-xl-12 ftco-animate">
                            <form method="post" enctype="multipart/form-data" action="#" class="billing-form ftco-bg-dark p-3 p-md-5">
                                {% csrf_token %}
                                <div class="row align-items-end">
                                    <div class="col-xl-12 ftco-animate">
                                        <button type="button" class="close" style="color: white" data-dismiss="modal">&times;</button>
                                        <h3 class="mb-4 billing-heading">Contáctenos</h3>
                                    </div>
                                </div>
                                <div class="row align-items-end">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="names">Nombre Completo</label>
                                            {% bootstrap_field form.nombre show_label=False %}
                                        </div>
                                    </div>
                                    <div class="w-100"></div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="names">Correo Electrónico</label>
                                            {% bootstrap_field form.correo show_label=False %}
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="names">Mensaje</label>
                                            {% bootstrap_field form.mensaje show_label=False %}
                                        </div>
                                    </div>
                                    <div class="w-100"></div>
                                    <div class="col-md-12 align-items-end">
                                        <div class="form-group mt-2">
                                            <div class="text-center w-full p-t-15 p-b-2">
                                                <input class="btn btn-white py-3 px-3"  type="submit"  value="Contactar Ahora" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock contenido %}
{% block js %}

{% endblock js %}

apps/tenants/templates/tenants/tenant_form.html
{% extends 'base_maravilla.html' %}
{# Load the tag library #}
{% load bootstrap4 %}
{% load staticfiles %}

{% block css %}
    <style type="text/css">
        option {
            color: black;
        }
    </style>
{% endblock css %}

{% block titulo %} Crear Tenant {% endblock titulo %}

{% block contenido %}

    <section class="ftco-section center">
        <div class = "container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span>
                <span class="mr-2"><a href="{% url 'tenants:tenants_listar' %}">Listar Tenants</a></span>
                <span>Crear Tenant</span></p>
            <div class="row justify-content-center">
                <div class="col-xl-9 ftco-animate">
                    <form method="post" enctype="multipart/form-data" action="#" class="billing-form ftco-bg-dark p-3 p-md-5 ">
                        {% csrf_token %}

                        <div class="row justify-content-center">
                            <div class="col-xl-9 ftco-animate">
                                <h3 class="mb-4 billing-heading">Crear Tenant</h3>
                            </div>
                            <div class="col-xl-3 ftco-animate ">
                                <p><a href="{% url 'tenants:tenants_listar' %}" style="width: 160px;" class="btn btn-white btn-outline-white p-2">Ver Tenants</a></p>
                            </div>
                        </div>
                        <div class="row align-items-end">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="name">Nombre</label>
                                    {% bootstrap_field form.nombre show_label=False %}
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="direccion">Dirección</label>
                                    {% bootstrap_field form.direccion show_label=False %}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="telefono">Teléfono</label>
                                    {% bootstrap_field form.telefono show_label=False %}
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="paquete">Paquete</label>
                                    {% bootstrap_field form.paquete show_label=False %}
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="fecha">Fecha Límite</label>
                                    {% bootstrap_field form.pagado_hasta show_label=False %}
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="dominio">Subdominio</label>
                                    {% bootstrap_field form.schema_name show_label=False %}
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-12 align-items-end">
                                <div class="form-group mt-2">
                                    <div class="text-center w-full p-t-15 p-b-15">
                                        <input class="btn btn-primary py-4 px-4"  type="submit"  value="Guardar Tenant" />
                                    </div>
                                </div>
                            </div>

                        </div>

                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock contenido %}

{% block js %}
    <script>
    </script>
{% endblock js %}

apps/tenants/templates/tenants/tenant_list.html
{% extends 'base_maravilla.html' %}
{# Load the tag library #}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/tenant-listar.css' %}">
    <style media="screen"></style>
{% endblock css %}

{% block titulo %} Tenants {% endblock titulo %}

{% block contenido %}
    <section class="ftco-section">
        <div class = "container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span><span>Lista de Tenants</span></p>

            <form action="#" class="billing-form ftco-bg-dark p-3 p-md-5">
                <div class="row justify-content-center">
                    <div class="col-xl-10 ftco-animate">
                        <h3 class="mb-4 billing-heading">Lista de Tenants</h3>
                    </div>
                    <div class="col-xl-2 ftco-animate">
                        <p><a href="{% url 'tenants:tenant_crear' %}" style="width: 143px;" class="btn btn-primary p-2">Crear Tenant</a></p>
                    </div>
                </div>
                <div class="table-responsive">
                    <table id="tabla_items" class="table table-striped">

                        <thead class="thead-dark">
                        <tr>
                            <th style="width: 10.5%" scope="col">Subdominio</th>
                            <th style="width: 10.5%" scope="col">Nombre</th>
                            <th style="width: 10.5%" scope="col">Paquete</th>
                            <th style="width: 10.5%" scope="col">Fecha Límite</th>
                            <th style="width: 12.5%" scope="col">Dirección</th>
                            <th style="width: 10.5%" scope="col">Teléfono</th>
                            <th style="width: 10.5%" scope="col">Estado</th>
                            <th style="width: 14%" scope="col">Acciones</th>
                        </tr>
                        </thead>
                        <tbody >
                        {% for dominio in dominios %}
                            <tr>
                                <td style="width: 10.5%">
                                    {{dominio.domain}}
                                </td>
                                <td style="width: 10.5%">
                                    {{dominio.tenant.nombre}}
                                </td>
                                <td style="width: 10.5%">
                                    {{dominio.tenant.paquete}}
                                </td>
                                <td  style="width: 10.5%">
                                    {{dominio.tenant.pagado_hasta}}
                                </td>
                                <td style="width: 12.5%">
                                    {{dominio.tenant.direccion}}
                                </td>
                                <td style="width: 10.5%">
                                    {{dominio.tenant.telefono}}
                                </td>
                                <td style="width: 10.5%">
                                    {{ dominio.tenant.estado|yesno:"Disponible,No disponible"}}
                                </td>
                                <td style="width: 14%">

                                    <p class="mb-1"><a href="{% url 'tenants:tenant_modificar' dominio.tenant.id %}"  class="btn btn-outline-warning custom-btn">Modificar</a></p>
                                    {% if dominio.tenant.estado == True %}
                                        <p><a href="{% url 'tenants:tenant_desactivar' dominio.tenant.id %}" class="btn btn-outline-danger custom-btn">Desactivar</a></p>
                                    {% else %}
                                        <p><a href="{% url 'tenants:tenant_activar' dominio.tenant.id %}" class="btn btn-outline-primary custom-btn">Activar</a></p>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                </div>

            </form>
        </div>
    </section>

{% endblock contenido %}

{% block js %}
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/jquery-3.3.1.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#tabla_items').DataTable({
                responsive: true
            });
        } );
    </script>

{% endblock js %}