apps/carrito/urls.py
from django.urls import path , include
from apps.carrito.views import *
from django.contrib.auth import views as auth_views
from apps.carrito import views

#from apps.accounts.decorators import check_recaptcha

app_name = 'carrito'

urlpatterns = [

    path('checkout/', checkout, name='checkout'),
    path('orden_detalle/', orden_detalle, name='orden_detalle'),
    path('agregar_a_carrito/<item_id>', agregar_a_carrito, name='agregar_a_carrito'),
    path('actualizar-transaccion/<token>', checkout, name='actualizar_transaccion'),
    path('borrar_de_carrito/<item_id>', borrar_de_carrito, name='borrar_de_carrito'),
    path('payment/<order_id>', process_payment, name='proceso_pago'),
    
    
    # url(r'^success/$', success, name='purchase_success'),

]

apps/productos/urls.py
from django.urls import path , include
from apps.productos.views import *
from django.contrib.auth import views as auth_views
from apps.productos import views

#from apps.accounts.decorators import check_recaptcha

app_name = "productos"

urlpatterns = [
    path('listar-productos', views.ProductosListar.as_view(), name='productos_listar'),
    path('listar-productos/<int:pk>', views.ProductoDetalle.as_view(), name='producto_detalle'),
    path('crear-producto', views.ProductoCrear.as_view(), name='producto_crear'),
    path('actualizar-producto/<int:pk>', views.ProductoActualizar.as_view(), name='producto_actualizar'),
    path('eliminar-producto/<int:pk>', views.ProductoEliminar.as_view(), name='producto_eliminar'),

    path('crear-combo', views.ComboCrear.as_view(), name='combo_crear'),
    path('listar-combos', views.ComboListar.as_view(), name='combos_listar'),


    path('listar-ingredientes', views.IngredientesListar.as_view(), name='ingredientes_listar'),
    path('listar-ingredientes/<int:pk>', views.IngredienteDetalle.as_view(), name='ingrediente_detalle'),
    path('crear-ingrediente', views.IngredienteCrear.as_view(), name='ingrediente_crear'),
    path('actualizar-ingrediente/<int:pk>', views.IngredienteActualizar.as_view(), name='ingrediente_actualizar'),
    path('eliminar-ingrediente/<int:pk>', views.IngredienteEliminar.as_view(), name='ingrediente_eliminar'),


    path('nuestro-menu/', views.Tienda.as_view(template_name='productos/menu.html'), name='menu'),
    path('tienda/', views.Tienda.as_view(template_name='productos/tienda.html'), name='tienda'),
    path('ver-item/<int:pk>', views.Item.as_view(template_name='productos/item.html'), name='item'),

]

apps/usuarios/urls.py
from django.urls import path , include
from apps.usuarios.views import *
from django.contrib.auth import views as auth_views
from apps.usuarios import views
#from apps.accounts.decorators import check_recaptcha

app_name = 'usuarios'

urlpatterns = [
    path('home', home, name='home'),
    path('dashboard', dashboard, name='dashboard'),
    path('registro', views.Registro.as_view(), name='registrarme'),
    path('mi-cuenta/<int:pk>', views.DatosActualizar.as_view(template_name='usuarios/datos.html'), name='datos'),
    path('contrasena/<int:pk>', views.ContrasenaActualizar.as_view(template_name='usuarios/contrasena.html'), name='contrasena'),
    path('desactivar/<int:id_usuario>', usuario_desactivar, name='desactivar'),

    path('crear-digitador', views.CrearDigitador.as_view(template_name='usuarios/digitador_crear.html'), name='crear_digitador'),
    path('listar-digitadores', views.DigitadoresListar.as_view(template_name='usuarios/digitador_list.html'), name='listar_digitadores'),
    path('ver-digitador/<int:pk>', views.UsuarioDetalle.as_view(template_name='usuarios/digitador_detail.html'), name='digitador_detalle'),
    path('pdf-digitadores/<int:staff>', pdf_usuario, name='pdf_digitadores'),

    path('listar-clientes', views.ClientesListar.as_view(template_name='usuarios/cliente_list.html'), name='listar_clientes'),
    path('ver-cliente/<int:pk>', views.UsuarioDetalle.as_view(template_name='usuarios/cliente_detail.html'), name='cliente_detalle'),
    path('pdf-clientes/<staff>', pdf_usuario, name='pdf_clientes'),


    path('login', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='usuarios/login.html'),
         name='login'),


    path('salir', auth_views.LogoutView.as_view(), name='salir'),
]

apps/productos/models.py
from django.db import models
from django_select2.forms import ModelSelect2Widget, Select2MultipleWidget


class Ingrediente(models.Model):


	nombre= models.CharField(max_length=200)
	precio_por_unidad = models.PositiveIntegerField()
	imagen = models.FileField(upload_to="productos_imagenes/", null=True, blank=True)

	def __str__(self):
		return self.nombre
class Producto(models.Model):

	TIPOS_PRODUCTOS = (
		("Carne/Pollo", "Carne/Pollo"),
		("Pasta", "Pasta"),
		("Comida Rápida", "Comida Rápida"),
		("Infantil", "Infantil"),
		("Bebida", "Bebida"),
		("Adición", "Adición")

	)
	nombre= models.CharField(max_length=200)
	descripcion = models.TextField(max_length=500, default=" ")
	tipo = models.CharField(max_length=15, choices=TIPOS_PRODUCTOS, default='Bebida')
	precio = models.PositiveIntegerField()
	cantidad = models.PositiveIntegerField(default=0)
	estado = models.BooleanField(default=True)
	imagen = models.FileField(upload_to="productos_imagenes/", null=True, blank=True)
	ingredientes = models.ManyToManyField(Ingrediente)

	def __str__(self):
		return self.nombre


class Combo(models.Model):

	nombre = models.CharField(max_length=200)
	descripcion = models.TextField(max_length=500, default=" ")
	precio = models.PositiveIntegerField()
	cantidad = models.PositiveIntegerField(default=0)
	estado = models.BooleanField(default=True)
	imagen = models.FileField(upload_to="productos_imagenes/", null=True, blank=True)
	productos = models.ManyToManyField(Producto)

apps/productos/forms.py
from django import forms
from django_select2.forms import ModelSelect2Widget, ModelSelect2MultipleWidget
from .models import *

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre','descripcion','cantidad','tipo','ingredientes','precio','imagen','estado']

        widgets={
        'ingredientes': ModelSelect2MultipleWidget(
        model = Ingrediente,
        search_fields=['nombre__icontains'],
        required = False,
        )}


class ComboForm(forms.Form):
    class Meta:
        model = Combo
        fields = '__all__'

        widgets = {
        'productos': ModelSelect2MultipleWidget(
        model = Ingrediente,
        search_fields=['nombre__icontains'],
        )
        }

apps/productos/views.py
from django.shortcuts import render
from apps.productos.models import *
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.db import connection
from apps.tenants.models import *
from django.contrib import messages
from .forms import *
from apps.carrito.views import *
# Create your views here.


class Tienda(ListView):
    model = Producto

    def get_context_data(self, **kwargs):
        context = super(Tienda, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        if self.request.user.is_authenticated:
            context['orden'] = get_orden_usuario_pendiente(self.request)
        return context


class Item(DetailView):
    model = Producto

    def get_context_data(self, **kwargs):
        context = super(Item, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        context['carne'] = Producto.objects.filter(tipo="Carne/Pollo", estado=True).last()
        context['pasta'] = Producto.objects.filter(tipo="Pasta", estado=True).last()
        context['rapida'] = Producto.objects.filter(tipo="Comida Rápida", estado=True).last()
        context['infantil'] = Producto.objects.filter(tipo="Infantil", estado=True).last()
        context['bebida'] = Producto.objects.filter(tipo="Bebida", estado=True).last()
        if self.request.user.is_authenticated:
            context['orden'] = get_orden_usuario_pendiente(self.request)
        return context


class ProductosListar(ListView):
    model = Producto

    def get_context_data(self, **kwargs):
        context = super(ProductosListar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context


class ProductoDetalle(DetailView):
    model = Producto

    def get_context_data(self, **kwargs):
        context = super(ProductoDetalle, self).get_context_data(**kwargs)
        prod = Producto.objects.get(pk = int(self.kwargs.get('pk')))
        context['ingredientes_list'] = prod.ingredientes.all()
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context


class ProductoCrear(SuccessMessageMixin, CreateView):
    model = Producto
    form_class = ProductoForm
    success_message = 'Producto agregado con exito'

    def form_valid(self, form):
        self.object = form.save(commit=False)

        total = form.cleaned_data.get('precio');
        for ing in form.cleaned_data.get('ingredientes'):
            total += ing.precio_por_unidad

        form.instance.precio = total
        return super(ProductoCrear, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductoCrear, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:productos_listar")


class ProductoActualizar(SuccessMessageMixin, UpdateView):
    model = Producto
    success_message = 'Producto modificado con exito'
    form_class = ProductoForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        total = form.cleaned_data.get('precio');
        for ing in form.cleaned_data.get('ingredientes'):
            total += ing.precio_por_unidad

        form.instance.precio = total
        return super(ProductoActualizar, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductoActualizar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:productos_listar")


class ProductoEliminar(DeleteView):
    model = Producto

    def get_context_data(self, **kwargs):
        context = super(ProductoEliminar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:productos_listar")


class ComboListar(ListView):
    model = Combo

    def get_context_data(self, **kwargs):
        context = super(ComboListar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context


class ComboDetalle(DetailView):
    model = Combo

    def get_context_data(self, **kwargs):
        context = super(ComboDetalle, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context


class ComboCrear(SuccessMessageMixin, CreateView):
    model = Combo
    success_message = 'Combo agregado con exito'
    form_class = ComboForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        total = 0
        for precio in form.cleaned_data.get('productos'):
            total += ing.precio

        form.instance.precio = total
        return super(ComboCrear, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ComboCrear, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:combos_listar")


class ComboActualizar(SuccessMessageMixin, UpdateView):
    model = Combo
    success_message = 'Combo modificado con exito'
    form_class = ComboForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        total = 0
        for precio in form.cleaned_data.get('productos'):
            total += ing.precio

        form.instance.precio = total
        return super(ComboActualizar, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ComboActualizar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:combos_listar")


class ComboEliminar(DeleteView):
    model = Combo

    def get_context_data(self, **kwargs):
        context = super(ComboEliminar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:combos_listar")



class IngredientesListar(ListView):
    model = Ingrediente

    def get_context_data(self, **kwargs):
        context = super(IngredientesListar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context


class IngredienteDetalle(DetailView):
    model = Ingrediente

    def get_context_data(self, **kwargs):
        context = super(IngredienteDetalle, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context


class IngredienteCrear(SuccessMessageMixin, CreateView):
    model = Ingrediente
    fields = '__all__'
    success_message = 'Ingrediente agregado con exito'

    def get_context_data(self, **kwargs):
        context = super(IngredienteCrear, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:ingredientes_listar")


class IngredienteActualizar(SuccessMessageMixin, UpdateView):
    model = Ingrediente
    success_message = 'Ingrediente modificado con exito'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(IngredienteActualizar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:ingredientes_listar")


class IngredienteEliminar(DeleteView):
    model = Ingrediente

    def get_context_data(self, **kwargs):
        context = super(IngredienteEliminar, self).get_context_data(**kwargs)
        context['usuario'] = self.request.user
        schema = connection.schema_name
        context['tenant'] = Tenant.objects.get(schema_name=schema)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("productos:ingredientes_listar")

apps/productos/templates/productos/ingrediente_detail.html
{% extends 'base_dash.html' %}
{# Load the tag library #}
{% load bootstrap4 %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="{% static 'coffee_template/css/producto-detalle.css' %}">
{% endblock css %}

{% block titulo %}Detalle Ingrediente{% endblock titulo %}

{% block contenido %}

    <section class="ftco-section center">
        <div class = "container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span> <span>Ver Ingrediente</span></p>
            <div class="row justify-content-center">
                <div class="col-xl-6 ftco-animate">
                    <form method="post" enctype="multipart/form-data" action="#" class="billing-form ftco-bg-dark p-3 p-md-5 ">
                        <div class="row justify-content-center">
                            <div class="col-xl-8 ftco-animate">
                                <h3 class="mb-4 billing-heading">Ver Ingrediente</h3>
                            </div>
                            <div class="col-xl-4 ftco-animate" >
                                <p><a href="{% url 'productos:ingredientes_listar' %}" style="width: 130px;" class="btn btn-white btn-outline-white p-2">Ver Ingredientes</a></p>
                            </div>
                        </div>
                        <div class="row align-items-end">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {% if object.imagen  %}
                                        <img style="width: 450px; height: 250px;" src="{{object.imagen.url}}" class="img img-fluid centerImage ">
                                    {% else %}
                                        <img style="width: 450px; height: 250px; " src="{% static 'imagenes (acomodar)/no_image.jpg' %}" class="img img-fluid centerImage">
                                    {% endif %}
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Nombre</label>
                                    <input class="form-control" id="id_nombre" type="text" name="nombre" placeholder="Nombre" value="{{object.nombre}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Precio</label>
                                    <input class="form-control" id="id_precio_por_unidad" type="number" name="precio_por_unidad" placeholder="Precio" value="{{object.precio_por_unidad}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Cantidad</label>
                                    <input class="form-control" id="id_cantidad" type="number" name="cantidad" placeholder="Cantidad" value="{{object.cantidad}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Unidad</label>
                                    <input class="form-control" id="id_unidad" type="text" name="unidad" placeholder="Nombre" value="{{object.unidad}}" disabled="true">

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock contenido %}
{% block js %}
    <script>
    </script>
{% endblock js %}

apps/productos/templates/productos/ingrediente_list.html
{% extends 'base_dash.html' %}
{# Load the tag library #}
{% load static %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/producto-listar.css' %}">

{% endblock css %}

{% block titulo %}Listar Ingredientes{% endblock titulo %}

{% block contenido %}

    <section class="ftco-section center">
        <div class="container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span>
                <span>Lista de Ingredientes</span></p>
            <form action="#" class="billing-form ftco-bg-dark p-3 p-md-5">
                <div class="row justify-content-center">
                    <div class="col-xl-10 ftco-animate">
                        <h3 class="mb-4 billing-heading">Lista de Ingredientes</h3>
                    </div>
                    <div class="col-xl-2 ftco-animate" >
                        <p><a href="{% url 'productos:ingrediente_crear' %}" style="width: 145px;" class="btn btn-primary p-2">Crear Ingrediente</a></p>
                    </div>
                </div>
                <div class="table-responsive">
                    <table id="example" class="table table-striped">
                        <thead class="thead-dark">
                        <tr>
                            <th style="width: 25%">Imagen</th>
                            <th style="width: 25%">Nombre</th>
                            <th style="width: 25%">Precio</th>
                            <th style="width: 25%">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ingrediente in ingrediente_list %}
                            <tr>
                                <td  style="width: 25%">
                                    {% if ingrediente.imagen  %}
                                        <img style="width: 150px; height: 110px;" src="{{ingrediente.imagen.url}}" class="img img-fluid centerImage ">
                                    {% else %}
                                        <img style="width: 150px; height: 110px; " src="{% static 'imagenes (acomodar)/no_image.jpg' %}" class="img img-fluid centerImage">
                                    {% endif %}
                                </td>
                                <td  style="width: 25%" >{{ingrediente.nombre}}</td>
                                <td  style="width: 25%">{{ingrediente.precio_por_unidad}}</td>
                                <td style="width: 25%">
                                    <p class="mb-1"><a href="{% url 'productos:ingrediente_detalle' ingrediente.id %}" class="btn btn-outline-info custom-btn">Ver Detalle</a></p>
                                    <p class="mb-1"><a href="{% url 'productos:ingrediente_actualizar' ingrediente.id %}" class="btn btn-outline-warning custom-btn">Modificar</a></p>
                                    <p><a href="{% url 'productos:ingrediente_eliminar' ingrediente.id %}" class="btn btn-outline-danger custom-btn">Eliminar</a></p>
                                    <div class="container">
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </section>
{% endblock contenido %}

{% block js %}
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/jquery-3.3.1.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'dist/js/dataTables.bootstrap4.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        } );
    </script>

{% endblock js %}

apps/productos/templates/productos/producto_detail.html
{% extends 'base_dash.html' %}
{# Load the tag library #}
{% load bootstrap4 %}
{% load static %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block css %}
    <link rel="stylesheet" href="{% static 'coffee_template/css/producto-detalle.css' %}">
{% endblock css %}

{% block titulo %}Detalle Producto{% endblock titulo %}

{% block contenido %}

    <section class="ftco-section center">
        <div class = "container">
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'usuarios:home' %}">Home</a></span> <span>Ver Producto</span></p>
            <div class="row justify-content-center">
                <div class="col-xl-6 ftco-animate">
                    <form method="post" enctype="multipart/form-data" action="#" class="billing-form ftco-bg-dark p-3 p-md-5 ">
                        <div class="row justify-content-center">
                            <div class="col-xl-8 ftco-animate">
                                <h3 class="mb-4 billing-heading">Ver producto</h3>
                            </div>
                            <div class="col-xl-4 ftco-animate" >
                                <p><a href="{% url 'productos:productos_listar' %}" style="width: 130px;" class="btn btn-white btn-outline-white p-2">Ver Inventario</a></p>
                            </div>
                        </div>
                        <div class="row align-items-end">
                            <div class="col-md-12">
                                <div class="form-group">
                                    {% if object.imagen  %}
                                        <img style="width: 450px; height: 250px;" src="{{object.imagen.url}}" class="img img-fluid centerImage ">
                                    {% else %}
                                        <img style="width: 450px; height: 250px; " src="{% static 'imagenes (acomodar)/no_image.jpg' %}" class="img img-fluid centerImage">
                                    {% endif %}
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="names">Nombre</label>
                                    <input class="form-control" id="id_nombre" type="text" name="nombre" placeholder="Nombre" value="{{object.nombre}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="names">Descripción</label>
                                    <textarea name="descripcion" cols="40" style="text-align:justify;" rows="5" maxlength="500" class="form-control"  disabled="true" required="" id="id_descripcion" > {{object.descripcion}}</textarea>
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Precio</label>
                                    <input class="form-control" id="id_precio" type="text" name="precio" placeholder="Precio" value="{{object.precio}}" disabled="true">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="names">Stock</label>
                                    <input class="form-control" id="id_estado" type="text" name="estado" placeholder="Estado" value="{{object.estado|yesno:"Disponible,No disponible"}}" disabled="true">
                                </div>
                            </div>
                            <div class="w-100"></div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="names">Ingredientes</label>

                                          {% for ing in ingredientes_list %}
                                          <input class="form-control" id="id_estado" type="text" name="estado"  value="{{ing.nombre}}" disabled="true">

                                          {% endfor %}
                              </div>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock contenido %}
{% block js %}
    <script>
    </script>
{% endblock js %}