apps/carrito/urls.py
from django.urls import path , include
from apps.carrito.views import *
from django.contrib.auth import views as auth_views
from apps.carrito import views

#from apps.accounts.decorators import check_recaptcha

app_name = 'carrito'

urlpatterns = [

    path('checkout/', checkout, name='checkout'),
    path('orden_detalle/', orden_detalle, name='orden_detalle'),
    path('agregar_a_carrito/<item_id>', agregar_a_carrito, name='agregar_a_carrito'),
    path('actualizar-transaccion/<token>', checkout, name='actualizar_transaccion'),
    path('borrar_de_carrito/<item_id>', borrar_de_carrito, name='borrar_de_carrito'),
    path('payment/<order_id>', process_payment, name='proceso_pago'),
    
    
    # url(r'^success/$', success, name='purchase_success'),

]

apps/productos/urls.py
from django.urls import path , include
from apps.productos.views import *
from django.contrib.auth import views as auth_views
from apps.productos import views

#from apps.accounts.decorators import check_recaptcha

app_name = "productos"

urlpatterns = [
    path('listar-productos', views.ProductosListar.as_view(), name='productos_listar'),
    path('listar-productos/<int:pk>', views.ProductoDetalle.as_view(), name='producto_detalle'),
    path('crear-producto', views.ProductoCrear.as_view(), name='producto_crear'),
    path('actualizar-producto/<int:pk>', views.ProductoActualizar.as_view(), name='producto_actualizar'),
    path('eliminar-producto/<int:pk>', views.ProductoEliminar.as_view(), name='producto_eliminar'),

    path('crear-combo', views.ComboCrear.as_view(), name='combo_crear'),
    path('listar-combos', views.ComboListar.as_view(), name='combos_listar'),


    path('listar-ingredientes', views.IngredientesListar.as_view(), name='ingredientes_listar'),
    path('listar-ingredientes/<int:pk>', views.IngredienteDetalle.as_view(), name='ingrediente_detalle'),
    path('crear-ingrediente', views.IngredienteCrear.as_view(), name='ingrediente_crear'),
    path('actualizar-ingrediente/<int:pk>', views.IngredienteActualizar.as_view(), name='ingrediente_actualizar'),
    path('eliminar-ingrediente/<int:pk>', views.IngredienteEliminar.as_view(), name='ingrediente_eliminar'),


    path('nuestro-menu/', views.Tienda.as_view(template_name='productos/menu.html'), name='menu'),
    path('tienda/', views.Tienda.as_view(template_name='productos/tienda.html'), name='tienda'),
    path('ver-item/<int:pk>', views.Item.as_view(template_name='productos/item.html'), name='item'),

]

apps/tenants/urls.py
from django.urls import path
from .views import *

app_name = 'tenants'
urlpatterns = [
    path('dashboard', dashboard, name='dashboard'),
    path('crear-tenant', tenant_crear , name='tenant_crear'),
    path('listar-tenants', tenants_listar , name='tenants_listar'),
    path('actualizar-tenant/<int:id_tenant>', tenant_modificar , name='tenant_modificar'),
    path('desactivar-tenant/<int:id_tenant>', tenant_desactivar, name='tenant_desactivar'),
    path('activar-tenant/<int:id_tenant>', tenant_activar, name='tenant_activar'),
]

apps/usuarios/urls.py
from django.urls import path , include
from apps.usuarios.views import *
from django.contrib.auth import views as auth_views
from apps.usuarios import views
#from apps.accounts.decorators import check_recaptcha

app_name = 'usuarios'

urlpatterns = [
    path('home', home, name='home'),
    path('dashboard', dashboard, name='dashboard'),
    path('registro', views.Registro.as_view(), name='registrarme'),
    path('mi-cuenta/<int:pk>', views.DatosActualizar.as_view(template_name='usuarios/datos.html'), name='datos'),
    path('contrasena/<int:pk>', views.ContrasenaActualizar.as_view(template_name='usuarios/contrasena.html'), name='contrasena'),
    path('desactivar/<int:id_usuario>', usuario_desactivar, name='desactivar'),

    path('crear-digitador', views.CrearDigitador.as_view(template_name='usuarios/digitador_crear.html'), name='crear_digitador'),
    path('listar-digitadores', views.DigitadoresListar.as_view(template_name='usuarios/digitador_list.html'), name='listar_digitadores'),
    path('ver-digitador/<int:pk>', views.UsuarioDetalle.as_view(template_name='usuarios/digitador_detail.html'), name='digitador_detalle'),
    path('pdf-digitadores/<int:staff>', pdf_usuario, name='pdf_digitadores'),

    path('listar-clientes', views.ClientesListar.as_view(template_name='usuarios/cliente_list.html'), name='listar_clientes'),
    path('ver-cliente/<int:pk>', views.UsuarioDetalle.as_view(template_name='usuarios/cliente_detail.html'), name='cliente_detalle'),
    path('pdf-clientes/<staff>', pdf_usuario, name='pdf_clientes'),


    path('login', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='usuarios/login.html'),
         name='login'),


    path('salir', auth_views.LogoutView.as_view(), name='salir'),
]

apps/tenants/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django_tenants.models import TenantMixin, DomainMixin
from django_tenants.postgresql_backend.base import _is_valid_schema_name
from apps.usuarios.models import Usuario
from datetime import datetime


class Tenant(TenantMixin):

    TIPOS_PAQUETES = (
        ("BÁSICO", "Básico"),
        ("STANDARD", "Standard"),
        ("PREMIUM", "Premium"),
    )

    """
    Modelo que representará a los tenants en el sistema
    """
    nombre = models.CharField(max_length=100,  blank=False)
    direccion = models.CharField(max_length=100,  blank=False)
    telefono = models.CharField(max_length=100,  blank=False)
    paquete = models.CharField(max_length=10, choices=TIPOS_PAQUETES)
    pagado_hasta = models.DateField(default=datetime.now)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre


class Dominio(DomainMixin):
    """
    Modelo que representará al dominio en el sistema
    """
    pass

templates/base_dash.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Franquicia Maravilla | {% block titulo %} {% endblock titulo %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'coffee_template/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
</head>

<style type="text/css">
    body {
      color: #c49b63 !important;
    }
</style>

{% block css %}
    <style type="text/css">
        .ftco-navbar-dark {
            border: 1px solid white !important;
        }
        body {
          color: #c49b63 !important;
        }
    </style>
{% endblock css %}
<body>

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'usuarios:home' %}">Maravilla<small>{{ tenant.nombre }}</small></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'usuarios:dashboard' %}" class="nav-link">Dashboard</a></li>
                {% if usuario.is_superuser %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Gestionar Usuarios</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item" href="{% url 'usuarios:listar_digitadores' %}">Digitadores</a>
                            <a class="dropdown-item" href="{% url 'usuarios:listar_clientes' %}">Clientes</a>
                        </div>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">Gestionar Tienda</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item" href="{% url 'productos:productos_listar' %}">Inventario</a>
                        <a class="dropdown-item" href="{% url 'productos:ingredientes_listar' %}">Ingredientes</a>
                        <a class="dropdown-item" href="#">Reporte de Ventas</a>
                    </div>
                </li>
               {% include 'nav_dash.html' %}
            </ul>
        </div>
    </div>
</nav>

<!-- END nav -->

{% block contenido %}

{% endblock contenido %}


<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


<script src="{% static 'coffee_template/js/jquery.min.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'coffee_template/js/popper.min.js' %}"></script>
<script src="{% static 'coffee_template/js/bootstrap.min.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'coffee_template/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'coffee_template/js/aos.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'coffee_template/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'coffee_template/js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<!-- <script src="{% static 'coffee_template/js/google-map.js' %}"></script> -->
<script src="{% static 'coffee_template/js/main.js' %}"></script>
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>


<script>
    {% for msg in messages %}
    $(document).ready(function () {
        setTimeout(function () {
            toastr.options = {
                "closeButtons": true,
                "progressBar": true,
                "preventDuplicates": true,
                "showEasing": "swing",
                "extendedTimeOut": 30000,
                "timeOut": 4000
            }
            toastr["{{ msg.tags }}"]("{{ msg }}")
        }, 500);
    });
    {% endfor %}
</script>
{% block js %}

{% endblock js %}
</body>
</html>

templates/base_maravilla.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Franquicia Maravilla | {% block titulo %} {% endblock titulo %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'coffee_template/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'coffee_template/css/market.css' %}">
    <link href="{% static 'dashboard_template/css/font-awesome.css' %}" rel="stylesheet">


    <script src="{% static 'dashboard_template/js/Chart.min.js' %}"></script>



</head>

{% block css %}
{% endblock css %}
<body>

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'usuarios:home' %}">Maravilla<small>Franquicias</small></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                {% if usuario.is_superuser %}
                    {% include 'nav_super.html' %}
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Tiendas</a>
                        {% for dominio in tenants %}
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                <a class="dropdown-item" href="{{dominio.domain}}">{{dominio.tenant.nombre}}</a>
                            </div>
                        {% endfor %}

                    </li>
                    <li class="nav-item"><a href="#section-counter" class="nav-link">Adquirir Franquicia</a></li>
                    <li class="nav-item active"><a href="{% url 'usuarios:login' %}" class="nav-link">Iniciar Sesión</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

{% block contenido %}

{% endblock contenido %}

<footer class="ftco-footer ftco-bg-dark">
    <div class="overlay"></div>
    <div class="container">
        <div class="row mb-5">
            <div class="col-lg-6 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Acerca de Nosotros</h2>
                    <p>La empresa Maravilla es una franquicia individual de carácter nacional para la elaboración, producción,
                        promoción y comercialización de alimentos procesados en diferentes líneas.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Servicios</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Elaboración</a></li>
                        <li><a href="#" class="py-2 d-block">Ventas</a></li>
                        <li><a href="#" class="py-2 d-block">Entregas</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">¿Preguntas?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">{{public.direccion}}, Cali, Valle del Cauca, Colombia</span></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+57 2 {{public.telefono}}</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">maravilla@gmail.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> Maravillapp.
                    Todos los derechos reservados.</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
        </div>
    </div>
</footer>



<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


<script src="{% static 'coffee_template/js/jquery.min.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'coffee_template/js/popper.min.js' %}"></script>
<script src="{% static 'coffee_template/js/bootstrap.min.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'coffee_template/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'coffee_template/js/aos.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'coffee_template/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'coffee_template/js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'coffee_template/js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<!-- <script src="{% static 'coffee_template/js/google-map.js' %}"></script> -->
<script src="{% static 'coffee_template/js/main.js' %}"></script>

{% block js %}

    <script type="application/javascript">
        $(function () {
            $('#id_pagado_hasta').datepicker({
                autoclose: true,
                format: 'dd/mm/yyyy',
                language: 'es',
                orientation: 'bottom',
                startDate: '+0d'
            });
        });
    </script>
{% endblock js %}

</body>
</html>

templates/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

templates/nav_dash.html
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">{{ usuario.username }}</a>
    <div class="dropdown-menu" aria-labelledby="dropdown04">
        <a class="dropdown-item" href="{% url 'usuarios:datos' usuario.id %}">Mi cuenta</a>
        <a class="dropdown-item" href="{% url 'usuarios:contrasena' usuario.id %}">Cambiar contraseña</a>
        <a class="dropdown-item" href="{% url 'usuarios:dashboard' %}">Dashboard</a>
        <a class="dropdown-item" href="{% url 'usuarios:salir' %}">Salir</a>
    </div>
</li>

templates/nav_login.html
<li class="nav-item cart"><a href="{% url 'carrito:orden_detalle' %}" class="nav-link"><span class="icon icon-shopping_cart"></span>
    <span class="bag d-flex justify-content-center align-items-center"><small>{{ orden.get_carrito_items|length }}</small></span></a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">{{ usuario.username }}</a>
    <div class="dropdown-menu" aria-labelledby="dropdown04">
        <a class="dropdown-item" href="{% url 'usuarios:datos' usuario.id %}">Mi cuenta</a>
        <a class="dropdown-item" href="{% url 'usuarios:contrasena' usuario.id %}">Cambiar contraseña</a>
        <a class="dropdown-item" href="{% url 'carrito:orden_detalle' %}">Carrito de Compras</a>
        <a class="dropdown-item" href="#">Mis Compras</a>
        <a class="dropdown-item" href="{% url 'usuarios:salir' %}">Salir</a>
    </div>
</li>

templates/nav_logout.html
<li class="nav-item active"><a href="{% url 'usuarios:login' %}" class="nav-link">Iniciar Sesión</a></li>
<li class="nav-item"><a href="{% url 'usuarios:registrarme' %}" class="nav-link">Registrarme</a></li>

templates/nav_super.html
<li class="nav-item active"><a href="{% url 'tenants:dashboard' %}" class="nav-link">Dashboard</a></li>
<li class="nav-item"><a href="{% url 'tenants:tenants_listar' %}" class="nav-link">Gestionar Tenants</a></li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">{{ usuario.username }}</a>
    <div class="dropdown-menu" aria-labelledby="dropdown04">
        <a class="dropdown-item" href="{% url 'tenants:dashboard' %}">Dashboard</a>
        <a class="dropdown-item" href="{% url 'usuarios:salir' %}">Salir</a>
    </div>
</li>